### ISSUE TITLE
Correct syntax for specifying TSIG algorithm for backends in the config

### ISSUE THREAD

**Issue by sebschrader** [vinyldns/vinyldns#1042]
**Describe the bug**
Specifying a TSIG `algorithm` for a backend in the API config with a HOCON string as documented in [config-api.md](https://github.com/vinyldns/vinyldns/blob/v0.9.10/modules/docs/src/main/mdoc/operator/config-api.md) does not work and yields a `pureconfig.error.ConfigReaderException` claiming `Expected type OBJECT. Found STRING instead.` for each `algorithm` field during startup.

I've studied #1011. Unfortunately I'm not familiar with HOCON/PureConfig or Scala enough, to understand what's exactly wrong.

**VinylDNS Version**
0.9.10

**To Reproduce**
Add a backend with an algorithm to the sample [Docker API config](https://github.com/vinyldns/vinyldns/blob/v0.9.10/docker/api/docker.conf) and start the `docker-compose-quick-start.yml` stack:

```shell
sudo VINYLDNS_VERSION=0.9.10 docker-compose -f docker-compose-quick-start.yml up -d
```

Use the following backend config below either `vinyldns.backend.backend-providers.settings` or `vinyldns`:
```hocon
  backends = [
    {
      id = "ns.example.com"
      zone-connection = {
        name = "vinyldns.example.com."
        key-name = "vinyldns.example.com."
        key = "xfKA0DYb88tiUGND+cWddwUg3/SugYSsdvCfBOJ1jr8MEdgbVRyrlVDEXLsfTUGorQ3ShENdymw2yw+rTr+lwA=="
        primary-server = "ns.example.com."
        algorithm = "HMAC-SHA512"
      }
      transfer-connection = {
        name = "vinyldns.example.com."
        key-name = "vinyldns.example.com."
        key = "xfKA0DYb88tiUGND+cWddwUg3/SugYSsdvCfBOJ1jr8MEdgbVRyrlVDEXLsfTUGorQ3ShENdymw2yw+rTr+lwA=="
        primary-server = "ns.example.com."
        algorithm = "HMAC-SHA512"
      }
      tsig-usage = "always"
      }
    }
  ]
```

Then check the logs of the API container:

```shell
sudo docker logs vinyldns-api
```

**Expected behavior**
Config should load with the documented syntax or the documentation should be updated with the correct syntax.

**Stack trace or error log output**

When configuring the backends below `vinyldns.backend.backend-providers.settings.backends`:
```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a vinyldns.api.backend.dns.DnsBackendProviderConfig. Failures are:
  at 'backends.2.transfer-connection.algorithm':
    - (/opt/docker/bin/../conf/application.conf: 87) Expected type OBJECT. Found STRING instead.
  at 'backends.2.zone-connection.algorithm':
    - (/opt/docker/bin/../conf/application.conf: 80) Expected type OBJECT. Found STRING instead.

        at pureconfig.module.catseffect.package$.$anonfun$loadF$5(package.scala:55)
        at cats.data.EitherT.$anonfun$bimap$1(EitherT.scala:369)
        at unsafeRunAsync @ vinyldns.api.Boot$.delayedEndpoint$vinyldns$api$Boot$1(Boot.scala:225)
        at delay$extension @ pureconfig.module.catseffect.package$.loadF(package.scala:53)
        at subflatMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:63)
        at leftMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:64)
        at rethrowT @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:65)
        at unsafeRunAsync @ vinyldns.api.Boot$.delayedEndpoint$vinyldns$api$Boot$1(Boot.scala:225)
        at use @ vinyldns.mysql.repository.MySqlDataStoreProvider.load(MySqlDataStoreProvider.scala:45)
        at unsafeRunAsync @ vinyldns.api.Boot$.delayedEndpoint$vinyldns$api$Boot$1(Boot.scala:225)
        at apply @ vinyldns.mysql.repository.MySqlDataStoreProvider.load(MySqlDataStoreProvider.scala:45)
        at apply @ vinyldns.mysql.repository.MySqlDataStoreProvider.load(MySqlDataStoreProvider.scala:45)
        at use @ vinyldns.mysql.repository.MySqlDataStoreProvider.load(MySqlDataStoreProvider.scala:45)
        at map @ vinyldns.api.backend.dns.DnsBackendProviderLoader.$anonfun$load$1(DnsBackendProviderLoader.scala:39)
        at subflatMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:63)
        at leftMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:64)
        at rethrowT @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:65)
```

When configuring the backends below `vinyldns.backends`:
```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a vinyldns.core.domain.zone.LegacyDnsBackend. Failures are:
  at 'transfer-connection.algorithm':
    - (/opt/docker/bin/../conf/application.conf: 163) Expected type OBJECT. Found STRING instead.
  at 'zone-connection.algorithm':
    - (/opt/docker/bin/../conf/application.conf: 156) Expected type OBJECT. Found STRING instead.

        at pureconfig.ConfigSource.loadOrThrow(ConfigSource.scala:80)
        at pureconfig.ConfigSource.loadOrThrow$(ConfigSource.scala:77)
        at pureconfig.ConfigObjectSource.loadOrThrow(ConfigSource.scala:91)
        at vinyldns.core.domain.zone.ConfiguredDnsConnections$.$anonfun$load$4(Zone.scala:234)
        at map @ vinyldns.core.crypto.CryptoAlgebra$.$anonfun$load$2(CryptoAlgebra.scala:31)
        at flatMap @ vinyldns.core.crypto.CryptoAlgebra$.load(CryptoAlgebra.scala:30)
        at map @ vinyldns.core.domain.zone.ConfiguredDnsConnections$.load(Zone.scala:201)
        at flatMap @ vinyldns.api.config.VinylDNSConfig$.$anonfun$load$22(VinylDNSConfig.scala:95)
        at subflatMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:63)
        at leftMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:64)
        at rethrowT @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:65)
        at flatMap @ vinyldns.api.config.VinylDNSConfig$.$anonfun$load$21(VinylDNSConfig.scala:94)
        at map @ vinyldns.core.crypto.CryptoAlgebra$.$anonfun$load$2(CryptoAlgebra.scala:31)
        at flatMap @ vinyldns.core.crypto.CryptoAlgebra$.load(CryptoAlgebra.scala:30)
        at flatMap @ vinyldns.api.config.VinylDNSConfig$.$anonfun$load$20(VinylDNSConfig.scala:93)
        at flatMap @ vinyldns.api.config.VinylDNSConfig$.$anonfun$load$18(VinylDNSConfig.scala:92)
        at flatMap @ vinyldns.api.config.VinylDNSConfig$.loadFromStringListIO$1(VinylDNSConfig.scala:77)
        at flatMap @ vinyldns.api.config.VinylDNSConfig$.$anonfun$load$16(VinylDNSConfig.scala:91)
        at subflatMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:63)
        at leftMap @ vinyldns.api.config.VinylDNSConfig$.loadIO(VinylDNSConfig.scala:64)
```

**Comment by sebschrader** [comment]
An even simpler way to reproduce is to change is to apply the following diff to [`docker/api/docker.conf`](https://github.com/vinyldns/vinyldns/blob/v0.9.10/docker/api/docker.conf):

```diff
diff --git a/docker/api/docker.conf b/docker/api/docker.conf
index a0ec1d68..32e7b9bf 100644
--- a/docker/api/docker.conf
+++ b/docker/api/docker.conf
@@ -54,8 +54,9 @@ vinyldns {
                 name = "vinyldns."
                 key-name = "vinyldns."
                 key-name = ${?DEFAULT_DNS_KEY_NAME}
-                key = "nzisn+4G2ldMn0q1CV3vsg=="
+                key = "xfKA0DYb88tiUGND+cWddwUg3/SugYSsdvCfBOJ1jr8MEdgbVRyrlVDEXLsfTUGorQ3ShENdymw2yw+rTr+lwA=="
                 key = ${?DEFAULT_DNS_KEY_SECRET}
+                algorithm = "HMAC-SHA512"
                 primary-server = "vinyldns-bind9"
                 primary-server = ${?DEFAULT_DNS_ADDRESS}
               }
@@ -63,8 +64,9 @@ vinyldns {
                 name = "vinyldns."
                 key-name = "vinyldns."
                 key-name = ${?DEFAULT_DNS_KEY_NAME}
-                key = "nzisn+4G2ldMn0q1CV3vsg=="
+                key = "xfKA0DYb88tiUGND+cWddwUg3/SugYSsdvCfBOJ1jr8MEdgbVRyrlVDEXLsfTUGorQ3ShENdymw2yw+rTr+lwA=="
                 key = ${?DEFAULT_DNS_KEY_SECRET}
+                algorithm = "HMAC-SHA512"
                 primary-server = "vinyldns-bind9"
                 primary-server = ${?DEFAULT_DNS_ADDRESS}
```
