### ISSUE TITLE
"group" Table unusable when using MySQL

### ISSUE THREAD

**Issue by shgigi** [vinyldns/vinyldns#1164]
"group" table cannot be created when using MySQL.
 
VinylDNS Version: 0.14.0

Steps to reproduce - Run VinylDNS API image

when the image tries to create the table and migrate the schema it fails.
The command used is:
CREATE TABLE groups (...)

The problem is 'group' is already a command in MySQL so when trying to create the table like that it fails.
instead, the table needs to be created as such:
CREATE TABLE \`groups\` (...)

I also tried to create it manually and after succeeding I noticed that all subsequent uses of the table fail for the same reason,
for example I tried creating an Administrators group but the query failed after "FROM group":

{"@timestamp":"2022-08-16T13:12:40.255Z", "log.level": "INFO", "message":"Request started by user 75effdf9-a5ca-452d-a23f-e5b0e3efbc30 | [trace.id](http://trace.id/)=c7fcfd3f-3aac-499e-a90b-ab7c6c7c0fbd", "ecs.version": "1.2.0","[service.name](http://service.name/)":"vinyldns-api","[service.node.name](http://service.node.name/)":"vinyldns-api","event.dataset":"vinyldns-api","[process.thread.name](http://process.thread.name/)":"scala-execution-context-global-18","log.logger":"vinyldns.api.route.MembershipRoute"}
{"@timestamp":"2022-08-16T13:12:40.289Z", "log.level":"ERROR", "message":"SQL execution failed (Reason: (conn=459) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups):\n\n   SELECT data FROM groups WHERE name = 'Administrators'\n", "ecs.version": "1.2.0","[service.name](http://service.name/)":"vinyldns-api","[service.node.name](http://service.node.name/)":"vinyldns-api","event.dataset":"vinyldns-api","[process.thread.name](http://process.thread.name/)":"scala-execution-context-global-18","log.logger":"scalikejdbc.StatementExecutor$$anon$1"}
{"@timestamp":"2022-08-16T13:12:40.297Z", "log.level": "WARN", "message":"monitor='Endpoint.createGroup' millis=123 fail=1", "ecs.version": "1.2.0","[service.name](http://service.name/)":"vinyldns-api","[service.node.name](http://service.node.name/)":"vinyldns-api","event.dataset":"vinyldns-api","[process.thread.name](http://process.thread.name/)":"scala-execution-context-global-18","log.logger":"vinyldns.core.route.Monitor"}
[ERROR] [08/16/2022 13:12:40.299] [scala-execution-context-global-18] [akka.actor.ActorSystemImpl(VinylDNS)] Exception during request - (conn=459) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups | [trace.id](http://trace.id/)=c7fcfd3f-3aac-499e-a90b-ab7c6c7c0fbd
java.sql.SQLSyntaxErrorException: (conn=459) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeQuery(DBConnectionAttributesWiredPreparedStatement.scala:64)
        at scalikejdbc.StatementExecutor.$anonfun$executeQuery$1(StatementExecutor.scala:396)
        at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:22)
        at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:376)
        at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply(StatementExecutor.scala:320)
        at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply$(StatementExecutor.scala:306)
        at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:376)
        at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply(StatementExecutor.scala:353)
        at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply$(StatementExecutor.scala:352)
        at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:376)
        at scalikejdbc.StatementExecutor.executeQuery(StatementExecutor.scala:396)
        at scalikejdbc.DBSession.$anonfun$collection$1(DBSession.scala:310)
        at scalikejdbc.LoanPattern.using(LoanPattern.scala:22)
        at scalikejdbc.LoanPattern.using$(LoanPattern.scala:20)
        at scalikejdbc.ActiveSession.using(DBSession.scala:836)
        at scalikejdbc.DBSession.collection(DBSession.scala:309)
        at scalikejdbc.DBSession.collection$(DBSession.scala:307)
        at scalikejdbc.ActiveSession.collection(DBSession.scala:836)
        at scalikejdbc.DBSession.iterable(DBSession.scala:358)
        at scalikejdbc.DBSession.iterable$(DBSession.scala:357)
        at scalikejdbc.ActiveSession.iterable(DBSession.scala:836)
        at scalikejdbc.DBSession.first(DBSession.scala:281)
        at scalikejdbc.DBSession.first$(DBSession.scala:280)
        at scalikejdbc.ActiveSession.first(DBSession.scala:836)
        at scalikejdbc.DBSessionWrapper.$anonfun$first$1(DBSessionWrapper.scala:48)
        at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:33)
        at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
        at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:32)
        at scalikejdbc.DBSessionWrapper.first(DBSessionWrapper.scala:48)
        at scalikejdbc.SQLToOption.result(SQL.scala:999)
        at scalikejdbc.SQLToOption.result$(SQL.scala:995)
        at scalikejdbc.SQLToOptionImpl.result(SQL.scala:1013)
        at scalikejdbc.SQLToOptionImpl.result(SQL.scala:1013)
        at scalikejdbc.SQLToResult.$anonfun$apply$24(SQL.scala:826)
        at scalikejdbc.SQLToResult.apply(SQL.scala:832)
        at scalikejdbc.SQLToResult.apply$(SQL.scala:820)
        at scalikejdbc.SQLToOptionImpl.apply(SQL.scala:1013)
        at vinyldns.mysql.repository.MySqlGroupRepository.$anonfun$getGroupByName$3(MySqlGroupRepository.scala:153)
        at scalikejdbc.DBConnection.readOnly(DBConnection.scala:211)
        at scalikejdbc.DBConnection.readOnly$(DBConnection.scala:209)
        at scalikejdbc.DB.readOnly(DB.scala:60)
        at scalikejdbc.DB$.$anonfun$readOnly$1(DB.scala:174)
        at scalikejdbc.LoanPattern.using(LoanPattern.scala:22)
        at scalikejdbc.LoanPattern.using$(LoanPattern.scala:20)
        at scalikejdbc.DB$.using(DB.scala:139)
        at scalikejdbc.DB$.readOnly(DB.scala:173)
        at vinyldns.mysql.repository.MySqlGroupRepository.$anonfun$getGroupByName$2(MySqlGroupRepository.scala:148)
        at flatMap @ vinyldns.core.route.Monitored.monitor(Monitor.scala:32)
        at map @ vinyldns.api.domain.membership.MembershipService.groupWithSameNameDoesNotExist(MembershipService.scala:283)
        at map @ vinyldns.api.Interfaces$.$anonfun$result$6(Interfaces.scala:55)
        at flatMap @ vinyldns.api.domain.membership.MembershipService.createGroup(MembershipService.scala:60)
        at flatMap @ vinyldns.api.domain.membership.MembershipService.createGroup(MembershipService.scala:60)
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups
 WHERE name = 'Administrators'' at line 2
Query is:
SELECT data
  FROM groups
 WHERE name = ?
       , parameters ['Administrators']
java thread: scala-execution-context-global-18
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeQuery(DBConnectionAttributesWiredPreparedStatement.scala:64)
        at scalikejdbc.StatementExecutor.$anonfun$executeQuery$1(StatementExecutor.scala:396)
        at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:22)
        at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:376)
        at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply(StatementExecutor.scala:320)
        at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply$(StatementExecutor.scala:306)
        at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:376)
        at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply(StatementExecutor.scala:353)
        at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply$(StatementExecutor.scala:352)
        at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:376)
        at scalikejdbc.StatementExecutor.executeQuery(StatementExecutor.scala:396)
        at scalikejdbc.DBSession.$anonfun$collection$1(DBSession.scala:310)
        at scalikejdbc.LoanPattern.using(LoanPattern.scala:22)
        at scalikejdbc.LoanPattern.using$(LoanPattern.scala:20)
        at scalikejdbc.ActiveSession.using(DBSession.scala:836)
        at scalikejdbc.DBSession.collection(DBSession.scala:309)
        at scalikejdbc.DBSession.collection$(DBSession.scala:307)
        at scalikejdbc.ActiveSession.collection(DBSession.scala:836)
        at scalikejdbc.DBSession.iterable(DBSession.scala:358)
        at scalikejdbc.DBSession.iterable$(DBSession.scala:357)
        at scalikejdbc.ActiveSession.iterable(DBSession.scala:836)
        at scalikejdbc.DBSession.first(DBSession.scala:281)
        at scalikejdbc.DBSession.first$(DBSession.scala:280)
        at scalikejdbc.ActiveSession.first(DBSession.scala:836)
        at scalikejdbc.DBSessionWrapper.$anonfun$first$1(DBSessionWrapper.scala:48)
        at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:33)
        at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
        at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:32)
        at scalikejdbc.DBSessionWrapper.first(DBSessionWrapper.scala:48)
        at scalikejdbc.SQLToOption.result(SQL.scala:999)
        at scalikejdbc.SQLToOption.result$(SQL.scala:995)
        at scalikejdbc.SQLToOptionImpl.result(SQL.scala:1013)
        at scalikejdbc.SQLToOptionImpl.result(SQL.scala:1013)
        at scalikejdbc.SQLToResult.$anonfun$apply$24(SQL.scala:826)
        at scalikejdbc.SQLToResult.apply(SQL.scala:832)
        at scalikejdbc.SQLToResult.apply$(SQL.scala:820)
        at scalikejdbc.SQLToOptionImpl.apply(SQL.scala:1013)
        at vinyldns.mysql.repository.MySqlGroupRepository.$anonfun$getGroupByName$3(MySqlGroupRepository.scala:153)
        at scalikejdbc.DBConnection.readOnly(DBConnection.scala:211)
        at scalikejdbc.DBConnection.readOnly$(DBConnection.scala:209)
        at scalikejdbc.DB.readOnly(DB.scala:60)
        at scalikejdbc.DB$.$anonfun$readOnly$1(DB.scala:174)
        at scalikejdbc.LoanPattern.using(LoanPattern.scala:22)
        at scalikejdbc.LoanPattern.using$(LoanPattern.scala:20)
        at scalikejdbc.DB$.using(DB.scala:139)
        at scalikejdbc.DB$.readOnly(DB.scala:173)
        at vinyldns.mysql.repository.MySqlGroupRepository.$anonfun$getGroupByName$2(MySqlGroupRepository.scala:148)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:103)
        at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:37)
        at cats.effect.IO.unsafeRunAsync(IO.scala:274)
        at cats.effect.IO.unsafeToFuture(IO.scala:362)
        at vinyldns.api.route.VinylDNSDirectives.$anonfun$authenticateAndExecuteWithEntity$3(VinylDNSDirectives.scala:177)
        at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1.$anonfun$directive$2(FutureDirectives.scala:97)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1.$anonfun$directive$3(FutureDirectives.scala:97)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:55)
        at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
        at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1.$anonfun$directive$2(FutureDirectives.scala:97)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$toStrictEntity$4(BasicDirectives.scala:407)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by shgigi** [comment]
application.conf used:

vinyldns {
  data-stores = ["mysql"]

  mysql {
    class-name = "vinyldns.mysql.repository.MySqlDataStoreProvider"

    settings {
        name = "vinyldns"
        driver = "org.mariadb.jdbc.Driver"
        migration-url = "jdbc:mariadb://DBServer:3306/?user=vinyl&password=password"
        url = "jdbc:mariadb://DBServer:3306/vinyldns?user=vinyl&password=password"
        user = "vinyl"
        password = "password"
        flyway-out-of-order = false
      }
    repositories {
      zone {}
      batch-change {}
      user {}
      record-set {}
      record-set-cache {}
      group {}
      membership {}
      group-change {}
      zone-change {}
      record-change {}
    }
  }

  queue {
    class-name = "vinyldns.mysql.queue.MySqlMessageQueueProvider"

    polling-interval = 250.millis
    messages-per-poll = 10
    max-retries = 50

    settings {
      name = "vinyldns"
      driver = "org.mariadb.jdbc.Driver"
      migration-url = "jdbc:mariadb://DBServer:3306/?user=vinyl&password=password"
      url = "jdbc:mariadb://DBServer:3306/vinyldns?user=vinyl&password=password"
      user = "vinyl"
      password = "password"

      connection-timeout-millis = 1000
      idle-timeout = 10000
      max-lifetime = 30000
      maximum-pool-size = 5
      minimum-idle = 0
      flyway-out-of-order = false

      my-sql-properties = {
        cachePrepStmts=true
        preStmtcacheSize=250
        prepStmtCacheSqlLimit=2048
        rewriteBtachedStatements=true
      }
    }
  }

  shared-approved-types = ["A", "CNAME", "PTR"]

  high-value-domains {
    regex-list = ["domain.name.*"]
    ip-list = [
      "x.x.x.x"
    ]
  }
  crypto {
    type = "vinyldns.core.crypto.JavaCrypto"
    secret = "generatedSecret"
  }

  manual-batch-review-enabled = false
  manual-review-domains = {
    domain-list = [
      "domain.name.*"
    ]
    ip-list = [
      "x.x.x.x"
    ]
    zone-name-list = [
      "[zone.name](http://zone.name/)."
    ]
  }

  rest {
  host = "0.0.0.0"
  port = 9000
}

}

**Comment by Jay07GIT** [comment]
> \n\n SELECT data FROM groups WHERE name = 'Administrators'\n", "ecs.version":

I could see the `select` statement in the logs which is odd, while creating `Schema ` and `tables`. 

For more understanding , could you help me to reproduce the issue by giving the detailed steps.?

**Comment by shgigi** [comment]
It seems the main problem is using MySQL 8 instead of 5.
`groups` is a reserved keyword there.
