### ISSUE TITLE
Portal docker image broken 

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#317]
**Describe the bug**
Running `bin/docker-up-vinyldns.sh` causes errors to show up in the portal image:

```
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:
2018-10-31T16:32:21.061170200Z 
1) No implementation for controllers.ChangeLogStore was bound.
  while locating controllers.ChangeLogStore
    for the 4th parameter of controllers.VinylDNS.<init>(VinylDNS.scala:94)
  while locating com.google.inject.Provider<controllers.VinylDNS>
    for the 3rd parameter of router.Routes.<init>(Routes.scala:33)
  at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:121):
Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
2018-10-31T16:32:21.061238800Z 
2) No implementation for controllers.UserAccountStore was bound.
  at Module.configure(Module.scala:38) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)
2018-10-31T16:32:21.061267000Z 
3) An exception was caught and reported. Message: No configuration setting found for key 'users'
  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
2018-10-31T16:32:21.061287900Z 
3 errors
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
at com.google.inject.Guice.createInjector(Guice.java:99)
at com.google.inject.Guice.createInjector(Guice.java:84)
at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'users'
at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
at play.api.ConfigLoader$.$anonfun$booleanLoader$2(Configuration.scala:1037)
at play.api.ConfigLoader$.$anonfun$booleanLoader$2$adapted(Configuration.scala:1037)
at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1026)
at play.api.Configuration.get(Configuration.scala:215)
at Module.userAccountStore(Module.scala:52)
at Module.configure(Module.scala:38)
at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
at com.google.inject.spi.Elements.getElements(Elements.java:110)
at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
at com.google.inject.spi.Elements.getElements(Elements.java:110)
at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
... 8 more
```

**VinylDNS Version**
0.8.0

**To Reproduce**
1. `./bin/docker-up-vinyldns.sh` 

**Expected behavior**
That the portal starts up

**Comment by nimaeskandary** [comment]
duplicate of #270
