### ISSUE TITLE
Ensure compatibility with JDK 11

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#321]
**Describe the bug**
API doesn't start up using jdk 11

**VinylDNS Version**
0.8.0-SNAPSHOT

**To Reproduce**
`sbt ";project api;clean;dockerComposeStop;dockerComposeUp;reStart"`

**Expected behavior**
API starts up successfully 

**Stack trace or error log output**
```
[test] ERROR | (Boot:149) | VINYLDNS SERVER UNABLE TO START java.lang.reflect.InvocationTargetException
api[ERROR] java.lang.reflect.InvocationTargetException
api[ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
api[ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
api[ERROR] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
api[ERROR] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
api[ERROR] 	at vinyldns.core.crypto.CryptoAlgebra$.$anonfun$load$3(CryptoAlgebra.scala:35)
api[ERROR] 	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:176)
api[ERROR] 	at cats.effect.IO.unsafeRunTimed(IO.scala:321)
api[ERROR] 	at cats.effect.IO.unsafeRunSync(IO.scala:240)
api[ERROR] 	at vinyldns.api.crypto.Crypto$.instance$lzycompute(Crypto.scala:26)
api[ERROR] 	at vinyldns.api.crypto.Crypto$.instance(Crypto.scala:26)
api[ERROR] 	at vinyldns.api.Boot$.$anonfun$runApp$2(Boot.scala:65)
api[ERROR] 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
api[ERROR] 	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
api[ERROR] 	at cats.effect.IO.unsafeRunAsync(IO.scala:258)
api[ERROR] 	at vinyldns.api.Boot$.delayedEndpoint$vinyldns$api$Boot$1(Boot.scala:145)
api[ERROR] 	at vinyldns.api.Boot$delayedInit$body.apply(Boot.scala:44)
api[ERROR] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
api[ERROR] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
api[ERROR] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
api[ERROR] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
api[ERROR] 	at scala.collection.immutable.List.foreach(List.scala:388)
api[ERROR] 	at scala.App.main(App.scala:76)
api[ERROR] 	at scala.App.main$(App.scala:74)
api[ERROR] 	at vinyldns.api.Boot$.main(Boot.scala:44)
api[ERROR] 	at vinyldns.api.Boot.main(Boot.scala)
api[ERROR] Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
api[ERROR] 	at vinyldns.core.crypto.JavaCrypto.<init>(JavaCrypto.scala:39)
api[ERROR] 	... 25 more
api[ERROR] Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
api[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
api[ERROR] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
api[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
api[ERROR] 	... 26 more

sbt:api> reStop
[info] Stopping application api (by killing the forked JVM) ...
api ... finished with exit code 143
[success] Total time: 0 s, completed Oct 31, 2018, 9:42:02 AM
sbt:api> reStop
[info] Application api not yet started
[success] Total time: 1 s, completed Oct 31, 2018, 9:48:05 AM
sbt:api> exit
[info] shutting down server
[INFO] [10/31/2018 09:48:07.109] [Thread-7] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

**Additional context**
Seems others have this issue, tried suggested solutions briefly but could not resolve 

relevant links:
* https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j
* https://stackoverflow.com/questions/46381242/intellij-sbt-based-scala-project-does-not-build-with-java-9
* https://github.com/scala/scala-dev/issues/529

**Comment by pauljamescleary** [comment]
We need to wholesale be on jdk 11, let's prioritize and make sure this is done

**Comment by pauljamescleary** [comment]
Closing this as complete, api images are published using JDK 11 now
