### ISSUE TITLE
[Docker] Portal container problems

### ISSUE THREAD

**Issue by NorseGaud** [vinyldns/vinyldns#336]
**Describe the bug**

After running ./bin/docker-up-vinyldns.sh, I see

```
 norsegaud@norsegaudnet  ~/vinyldns   master  docker container ls -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                        PORTS                                          NAMES
ace09937d12b        vinyldns/portal:0.8.0                  "/opt/docker/bin/por…"   5 minutes ago       Exited (255) 12 seconds ago                                                  vinyldns-portal
a40a4851d624        vinyldns/api:0.8.0                     "/opt/docker/bin/boot"   5 minutes ago       Up 5 minutes                  0.0.0.0:9000->9000/tcp                         vinyldns-api
748e35cfc6d9        cnadiminti/dynamodb-local:2017-02-16   "/docker-entrypoint.…"   5 minutes ago       Up 5 minutes                  0.0.0.0:19000->8000/tcp                        vinyldns-dynamodb
58b3e2a1a83c        vinyldns/bind9:0.0.1                   "/entrypoint.sh"         5 minutes ago       Up 5 minutes                  0.0.0.0:19001->53/tcp, 0.0.0.0:19001->53/udp   vinyldns-bind9
2ebcabfaeb17        mysql:5.7                              "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes                  33060/tcp, 0.0.0.0:19002->3306/tcp             vinyldns-mysql
9dea0f2ca8c2        s12v/elasticmq:0.13.8                  "java -Djava.net.pre…"   5 minutes ago       Up 5 minutes                  0.0.0.0:9324->9324/tcp                         vinyldns-elasticmq
```
Notice the exited container. Logs are saying:

```
norsegaud@norsegaudnet  ~/vinyldns   master  docker logs ace09937d12b 
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for controllers.ChangeLogStore was bound.
  while locating controllers.ChangeLogStore
    for the 4th parameter of controllers.VinylDNS.<init>(VinylDNS.scala:94)
  while locating com.google.inject.Provider<controllers.VinylDNS>
    for the 3rd parameter of router.Routes.<init>(Routes.scala:33)
  at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:121):
Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

2) No implementation for controllers.UserAccountStore was bound.
  at Module.configure(Module.scala:38) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)

3) An exception was caught and reported. Message: No configuration setting found for key 'users'
  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'users'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
	at play.api.ConfigLoader$.$anonfun$booleanLoader$2(Configuration.scala:1037)
	at play.api.ConfigLoader$.$anonfun$booleanLoader$2$adapted(Configuration.scala:1037)
	at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1026)
	at play.api.Configuration.get(Configuration.scala:215)
	at Module.userAccountStore(Module.scala:52)
	at Module.configure(Module.scala:38)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 8 more
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for controllers.ChangeLogStore was bound.
  while locating controllers.ChangeLogStore
    for the 4th parameter of controllers.VinylDNS.<init>(VinylDNS.scala:94)
  while locating com.google.inject.Provider<controllers.VinylDNS>
    for the 3rd parameter of router.Routes.<init>(Routes.scala:33)
  at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:121):
Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

2) No implementation for controllers.UserAccountStore was bound.
  at Module.configure(Module.scala:38) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)

3) An exception was caught and reported. Message: No configuration setting found for key 'users'
  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'users'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
	at play.api.ConfigLoader$.$anonfun$booleanLoader$2(Configuration.scala:1037)
	at play.api.ConfigLoader$.$anonfun$booleanLoader$2$adapted(Configuration.scala:1037)
	at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1026)
	at play.api.Configuration.get(Configuration.scala:215)
	at Module.userAccountStore(Module.scala:52)
	at Module.configure(Module.scala:38)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 8 more
```

**VinylDNS Version**

0.8.0

**Additional context**

Attempting to get something working for Travis CI

**Comment by nimaeskandary** [comment]
Hey @NorseGaud! Thanks for reporting, we are currently tracking this in https://github.com/vinyldns/vinyldns/pull/319. Issue was some config misalignments since we are not regularly releasing right now but were still updating a conf file that is mounted into the image. One that's merged the portal image will be working again

**Comment by nimaeskandary** [comment]
closing in favor of #270
