### ISSUE TITLE
Quickstart script doesn't work

### ISSUE THREAD

**Issue by comcast-jonm** [vinyldns/vinyldns#887]
**Describe the bug**
Following the [quickstart](https://github.com/vinyldns/vinyldns/blob/master/README.md#quickstart) instructions from a fresh checkout does not result in a working local VinylDNS:

```
$ ./bin/docker-up-vinyldns.sh 
timeout is set to 60
vinyldns version is set to '0.9.4-SNAPSHOT'
Starting vinyldns and all dependencies in the background...
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "docker_default" with the default driver
Creating vinyldns-ldap       ... done
Creating vinyldns-bind9      ... done
Creating vinyldns-localstack ... done
Creating vinyldns-mysql      ... done
Creating vinyldns-api        ... done
Creating vinyldns-portal     ... done
Waiting for api...
pinging http://localhost:9000 ...
Retrying
...
Retrying
Exceeded retries waiting for http://localhost:9000 to be ready, failing
```

**VinylDNS Version**

`master` branch as of commit 1100f3d1f77ae8e64bf58f1281343ef0fd0ae50d

**To Reproduce**
1. `git clone https://github.com/vinyldns/vinyldns.git`
2. `./bin/docker-up-vinyldns.sh`
 
**Expected behavior**
Working local VinylDNS.

**Screenshots**
N/A

**Stack trace or error log output**
If I do a `docker logs vinyldns-api`, it has the following stacktrace:
```
...
Caused by: java.net.UnknownHostException: vinyldns-dynamodb
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy4.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074)
	... 23 more
```
The issue here seems to be that `docker-compose-build.yml` spins up a local DynamoDB via `localstack`, but `.env` sets `DYNAMODB_ENDPOINT=http://vinyldns-dynamodb:8000`, resulting in the API not being able to find it (the endpoint should probably be `http://vinyldns-localstack:19000`).

**Additional context**
N/A

**Comment by comcast-jonm** [comment]
I have a patch I believe will fix this; will raise as a PR shortly. Thanks!

**Comment by pauljamescleary** [comment]
@comcast-jonm I just peaked at this, part of this is recent merges, some of it is testing on a new build process that releases stuff as `-SNAPSHOT` ... I am going to make sure the `0.9.4-SNAPSHOT` looks good

**Comment by pauljamescleary** [comment]
@comcast-jonm I just confirmed that

1. `0.9.4-SNAPSHOT` does look good
2. The issue does pertain to the `DYNAMODB_ENDPOINT` being incorrect.

It is not tidy to have the `.env` file shared by two different `docker-compose.yml` files now that what is used for local testing has deviated from the quick start and func tests (which is necessary).

**Comment by comcast-jonm** [comment]
Ok, my local fix was to basically copy the `.env` file to something like `.env.build` and reference that from `docker-compose-build.yml` instead (after updating `DYNAMODB_ENDPOINT`). If that roughly sounds good, I will open an PR.

**Comment by pauljamescleary** [comment]
@comcast-jonm sounds good :)

**Comment by pauljamescleary** [comment]
Also @comcast-jonm feel free to add yourself to `AUTHORS.md` if interested
